name:                Hlex
version:             0.1.0.0
github:              "SebTee/Hlex"
license:             MIT
copyright:           "2023 Sebastian Tee"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/SebTee/Hlex#readme>

dependencies:
- base >= 4.7 && < 5
- regex-tdfa
- split

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  Hlex-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hlex
    - HUnit
